#!/usr/bin/env node
/**
 * Snippet Verification Tests
 * Validates that code examples in skills actually work
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const TMP_DIR = '/tmp/skill-tests';
let PASSED = 0;
let FAILED = 0;

function test(name, fn) {
  try {
    fn();
    console.log(`  ✅ ${name}`);
    PASSED++;
  } catch (err) {
    console.log(`  ❌ ${name}: ${err.message}`);
    FAILED++;
  }
}

function cleanup() {
  if (fs.existsSync(TMP_DIR)) {
    fs.rmSync(TMP_DIR, { recursive: true });
  }
  fs.mkdirSync(TMP_DIR, { recursive: true });
}

// ============================================
// pdf-processing tests
// ============================================

async function testPdfProcessing() {
  console.log('\n📄 pdf-processing snippets');
  
  // Test 1: pdf-parse loads
  test('pdf-parse module loads', () => {
    const pdf = require('pdf-parse');
    if (!pdf) throw new Error('Failed to load pdf-parse');
  });

  // Test 2: pdfkit generates PDF
  test('pdfkit generates valid PDF', () => {
    const PDFDocument = require('pdfkit');
    const doc = new PDFDocument();
    const outputPath = path.join(TMP_DIR, 'pdfkit-test.pdf');
    const stream = fs.createWriteStream(outputPath);
    
    doc.pipe(stream);
    doc.fontSize(20).text('Test PDF', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text('Generated by snippet verification');
    doc.end();
    
    // Wait for stream to finish
    return new Promise((resolve, reject) => {
      stream.on('finish', () => {
        const stats = fs.statSync(outputPath);
        if (stats.size === 0) reject(new Error('PDF is empty'));
        else resolve();
      });
      stream.on('error', reject);
    });
  });

  // Test 3: pdf-lib loads and creates PDF
  test('pdf-lib creates PDF', async () => {
    const { PDFDocument } = require('pdf-lib');
    const doc = await PDFDocument.create();
    const page = doc.addPage([500, 500]);
    
    const pdfBytes = await doc.save();
    const outputPath = path.join(TMP_DIR, 'pdflib-test.pdf');
    fs.writeFileSync(outputPath, pdfBytes);
    
    if (!fs.existsSync(outputPath)) throw new Error('PDF not saved');
    if (fs.statSync(outputPath).size === 0) throw new Error('PDF is empty');
  });

  // Test 4: pdf-lib merge pattern
  test('pdf-lib merge pattern works', async () => {
    const { PDFDocument } = require('pdf-lib');
    
    // Create two simple PDFs
    const doc1 = await PDFDocument.create();
    doc1.addPage([500, 500]);
    const bytes1 = await doc1.save();
    
    const doc2 = await PDFDocument.create();
    doc2.addPage([500, 500]);
    const bytes2 = await doc2.save();
    
    // Write temp files
    const path1 = path.join(TMP_DIR, 'merge1.pdf');
    const path2 = path.join(TMP_DIR, 'merge2.pdf');
    fs.writeFileSync(path1, bytes1);
    fs.writeFileSync(path2, bytes2);
    
    // Merge
    const merged = await PDFDocument.create();
    const pdf1 = await PDFDocument.load(bytes1);
    const pdf2 = await PDFDocument.load(bytes2);
    
    const pages1 = await merged.copyPages(pdf1, pdf1.getPageIndices());
    pages1.forEach(p => merged.addPage(p));
    
    const pages2 = await merged.copyPages(pdf2, pdf2.getPageIndices());
    pages2.forEach(p => merged.addPage(p));
    
    const mergedBytes = await merged.save();
    const outputPath = path.join(TMP_DIR, 'merged.pdf');
    fs.writeFileSync(outputPath, mergedBytes);
    
    // Verify merged PDF has 2 pages
    const loaded = await PDFDocument.load(mergedBytes);
    if (loaded.getPageCount() !== 2) {
      throw new Error(`Expected 2 pages, got ${loaded.getPageCount()}`);
    }
  });
}

// ============================================
// spreadsheet-processing tests
// ============================================

async function testSpreadsheetProcessing() {
  console.log('\n📊 spreadsheet-processing snippets');
  
  // Test 1: ExcelJS loads
  test('ExcelJS module loads', () => {
    const ExcelJS = require('exceljs');
    if (!ExcelJS) throw new Error('Failed to load exceljs');
  });

  // Test 2: Create workbook with columns
  test('ExcelJS creates workbook with columns', async () => {
    const ExcelJS = require('exceljs');
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Test Sheet');
    
    sheet.columns = [
      { header: 'Date', key: 'date', width: 15 },
      { header: 'Product', key: 'product', width: 20 },
      { header: 'Quantity', key: 'quantity', width: 12 },
      { header: 'Revenue', key: 'revenue', width: 15 }
    ];
    
    sheet.addRow({ date: '2024-01-01', product: 'Widget', quantity: 10, revenue: 100 });
    sheet.addRow({ date: '2024-01-02', product: 'Gadget', quantity: 5, revenue: 250 });
    
    const outputPath = path.join(TMP_DIR, 'test.xlsx');
    await workbook.xlsx.writeFile(outputPath);
    
    if (!fs.existsSync(outputPath)) throw new Error('XLSX not saved');
    if (fs.statSync(outputPath).size === 0) throw new Error('XLSX is empty');
  });

  // Test 3: Read and modify existing workbook
  test('ExcelJS reads and modifies workbook', async () => {
    const ExcelJS = require('exceljs');
    
    // Create initial workbook
    const wb1 = new ExcelJS.Workbook();
    const sheet1 = wb1.addWorksheet('Data');
    sheet1.addRow(['Name', 'Value']);
    sheet1.addRow(['Test', 100]);
    
    const testPath = path.join(TMP_DIR, 'read-test.xlsx');
    await wb1.xlsx.writeFile(testPath);
    
    // Read it back
    const wb2 = new ExcelJS.Workbook();
    await wb2.xlsx.readFile(testPath);
    
    const sheet2 = wb2.getWorksheet('Data');
    const value = sheet2.getCell('B2').value;
    
    if (value !== 100) throw new Error(`Expected 100, got ${value}`);
  });

  // Test 4: Add formula
  test('ExcelJS adds formulas', async () => {
    const ExcelJS = require('exceljs');
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Formulas');
    
    sheet.getCell('A1').value = 10;
    sheet.getCell('A2').value = 20;
    sheet.getCell('A3').value = { formula: 'SUM(A1:A2)' };
    
    // Note: ExcelJS preserves formulas but doesn't calculate them
    const formula = sheet.getCell('A3').formula;
    if (formula !== 'SUM(A1:A2)') {
      throw new Error(`Formula mismatch: ${formula}`);
    }
  });

  // Test 5: Apply formatting
  test('ExcelJS applies formatting', async () => {
    const ExcelJS = require('exceljs');
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Formatting');
    
    const cell = sheet.getCell('A1');
    cell.value = 'Formatted';
    cell.font = { name: 'Arial', size: 14, bold: true };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4472C4' } };
    
    // Verify formatting was set
    if (!cell.font.bold) throw new Error('Font bold not set');
    if (cell.fill.pattern !== 'solid') throw new Error('Fill pattern not set');
  });

  // Test 6: CSV operations
  test('ExcelJS handles CSV', async () => {
    const ExcelJS = require('exceljs');
    
    // Create and save a CSV
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('CSV Data');
    sheet.addRow(['Name', 'Age']);
    sheet.addRow(['Alice', 30]);
    sheet.addRow(['Bob', 25]);
    
    const csvPath = path.join(TMP_DIR, 'test.csv');
    await workbook.csv.writeFile(csvPath);
    
    if (!fs.existsSync(csvPath)) throw new Error('CSV not saved');
    
    // Read it back
    const wb2 = new ExcelJS.Workbook();
    await wb2.csv.readFile(csvPath);
    
    const sheet2 = wb2.getWorksheet(1);
    const value = sheet2.getCell('A2').value;
    if (value !== 'Alice') throw new Error(`Expected 'Alice', got ${value}`);
  });
}

// ============================================
// screenshot-capture tests
// ============================================

function testScreenshotCapture() {
  console.log('\n📸 screenshot-capture snippets');
  
  const platform = process.platform;
  
  // Test 1: Detect available tools
  test('Detects screenshot tools', () => {
    let found = false;
    
    if (platform === 'darwin') {
      try {
        execSync('which screencapture 2>/dev/null', { stdio: 'pipe' });
        found = true;
      } catch {}
    } else if (platform === 'linux') {
      const tools = ['scrot', 'gnome-screenshot', 'import'];
      for (const tool of tools) {
        try {
          execSync(`which ${tool} 2>/dev/null`, { stdio: 'pipe' });
          found = true;
          break;
        } catch {}
      }
    }
    
    // We don't fail if not found - just note it
    if (!found) {
      console.log('    ⚠️  No native screenshot tools found (expected on some systems)');
    }
  });

  // Test 2: Playwright availability
  test('Playwright CLI available', () => {
    try {
      execSync('npx playwright --version 2>/dev/null', { stdio: 'pipe' });
    } catch {
      throw new Error('Playwright not available - install with: npm install @playwright/test');
    }
  });
}

// ============================================
// create-plan tests (documentation only)
// ============================================

function testCreatePlan() {
  console.log('\n📝 create-plan (documentation-only skill)');
  
  // This skill has no code snippets - it only provides guidance
  // We verify the skill file exists and is parseable
  test('SKILL.md exists and is readable', () => {
    const skillPath = path.join(__dirname, '../skills/create-plan/SKILL.md');
    if (!fs.existsSync(skillPath)) {
      throw new Error('SKILL.md not found');
    }
    
    const content = fs.readFileSync(skillPath, 'utf8');
    
    // Verify it has required structure
    if (!content.includes('name:')) throw new Error('Missing name field');
    if (!content.includes('description:')) throw new Error('Missing description field');
    if (!content.includes('# Plan')) throw new Error('Missing plan template');
    if (!content.includes('## Scope')) throw new Error('Missing scope section');
    if (!content.includes('## Action items')) throw new Error('Missing action items section');
  });
}

// ============================================
// Main execution
// ============================================

async function main() {
  console.log('=== Snippet Verification Tests ===');
  console.log(`Temp directory: ${TMP_DIR}`);
  
  cleanup();
  
  try {
    testCreatePlan();
    await testPdfProcessing();
    await testSpreadsheetProcessing();
    testScreenshotCapture();
    
    // Summary
    console.log('\n=== Summary ===');
    console.log(`✅ Passed: ${PASSED}`);
    console.log(`❌ Failed: ${FAILED}`);
    
    if (FAILED === 0) {
      console.log('\n✅ All snippet tests passed!');
      process.exit(0);
    } else {
      console.log(`\n❌ ${FAILED} test(s) failed`);
      process.exit(1);
    }
  } catch (err) {
    console.error('Test runner error:', err);
    process.exit(1);
  }
}

main();
